version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.11
      - image: cimg/postgres:15.5
    environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_dby  
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Upload coverage
          command: |
            curl -s https://codecov.io/bash | bash

workflows:
  test-workflow:
    jobs:
      - test
